export const data = [
    {
        "name": "Pidgey1",
        "species": "Pidgey",
        "cp": "384",
        "hp": "56",
        "weight": "2.31",
        "height": "0.34",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "694",
        "hp_new": "84",
        "weight_new": "2.6",
        "height_new": "1.24",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey2",
        "species": "Pidgey",
        "cp": "366",
        "hp": "54",
        "weight": "1.67",
        "height": "0.29",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "669",
        "hp_new": "81",
        "weight_new": "1.93",
        "height_new": "1.05",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey3",
        "species": "Pidgey",
        "cp": "353",
        "hp": "55",
        "weight": "1.94",
        "height": "0.3",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "659",
        "hp_new": "83",
        "weight_new": "3.51",
        "height_new": "1.11",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey4",
        "species": "Pidgey",
        "cp": "338",
        "hp": "51",
        "weight": "1.73",
        "height": "0.31",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "640",
        "hp_new": "79",
        "weight_new": "30",
        "height_new": "1.12",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey5",
        "species": "Pidgey",
        "cp": "242",
        "hp": "45",
        "weight": "1.44",
        "height": "0.27",
        "power_up_stardust": "1900",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "457",
        "hp_new": "69",
        "weight_new": "1.42",
        "height_new": "0.98",
        "power_up_stardust_new": "1900",
        "power_up_candy_new": "2",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey6",
        "species": "Pidgey",
        "cp": "129",
        "hp": "35",
        "weight": "2.07",
        "height": "0.35",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "243",
        "hp_new": "52",
        "weight_new": "30",
        "height_new": "1.27",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey7",
        "species": "Pidgey",
        "cp": "10",
        "hp": "10",
        "weight": "0.92",
        "height": "0.25",
        "power_up_stardust": "200",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "15",
        "hp_new": "13",
        "weight_new": "30",
        "height_new": "0.9",
        "power_up_stardust_new": "200",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey8",
        "species": "Pidgey",
        "cp": "25",
        "hp": "14",
        "weight": "2.72",
        "height": "0.37",
        "power_up_stardust": "200",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "47",
        "hp_new": "21",
        "weight_new": "2.63",
        "height_new": "1.35",
        "power_up_stardust_new": "200",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey9",
        "species": "Pidgey",
        "cp": "24",
        "hp": "13",
        "weight": "2.07",
        "height": "0.32",
        "power_up_stardust": "200",
        "power_up_candy": "1",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "47",
        "hp_new": "21",
        "weight_new": "3.27",
        "height_new": "1.16",
        "power_up_stardust_new": "200",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey10",
        "species": "Pidgey",
        "cp": "161",
        "hp": "35",
        "weight": "1.45",
        "height": "0.31",
        "power_up_stardust": "1000",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "305",
        "hp_new": "54",
        "weight_new": "30",
        "height_new": "1.14",
        "power_up_stardust_new": "1000",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey11",
        "species": "Pidgey",
        "cp": "114",
        "hp": "31",
        "weight": "1.58",
        "height": "0.26",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "213",
        "hp_new": "47",
        "weight_new": "4.65",
        "height_new": "0.96",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey12",
        "species": "Pidgey",
        "cp": "333",
        "hp": "52",
        "weight": "1.85",
        "height": "0.3",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "633",
        "hp_new": "80",
        "weight_new": "2.54",
        "height_new": "1.1",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey13",
        "species": "Pidgey",
        "cp": "132",
        "hp": "33",
        "weight": "1.63",
        "height": "0.28",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "247",
        "hp_new": "50",
        "weight_new": "2.41",
        "height_new": "1.03",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey14",
        "species": "Pidgey",
        "cp": "60",
        "hp": "21",
        "weight": "1.67",
        "height": "0.3",
        "power_up_stardust": "400",
        "power_up_candy": "1",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "113",
        "hp_new": "33",
        "weight_new": "0.28",
        "height_new": "1.09",
        "power_up_stardust_new": "400",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey15",
        "species": "Pidgey",
        "cp": "42",
        "hp": "19",
        "weight": "2.01",
        "height": "0.3",
        "power_up_stardust": "400",
        "power_up_candy": "1",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "79",
        "hp_new": "29",
        "weight_new": "4.87",
        "height_new": "1.11",
        "power_up_stardust_new": "400",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey16",
        "species": "Pidgey",
        "cp": "91",
        "hp": "29",
        "weight": "2.68",
        "height": "0.35",
        "power_up_stardust": "600",
        "power_up_candy": "1",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "173",
        "hp_new": "44",
        "weight_new": "5.42",
        "height_new": "1.3",
        "power_up_stardust_new": "600",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey17",
        "species": "Pidgey",
        "cp": "139",
        "hp": "34",
        "weight": "1.76",
        "height": "0.31",
        "power_up_stardust": "1000",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "265",
        "hp_new": "53",
        "weight_new": "30",
        "height_new": "1.13",
        "power_up_stardust_new": "1000",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey18",
        "species": "Pidgey",
        "cp": "330",
        "hp": "48",
        "weight": "1.62",
        "height": "0.29",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "624",
        "hp_new": "75",
        "weight_new": "0.02",
        "height_new": "1.08",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": "weight_new is accurate"
    },
    {
        "name": "Pidgey19",
        "species": "Pidgey",
        "cp": "328",
        "hp": "48",
        "weight": "1.62",
        "height": "0.3",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "619",
        "hp_new": "76",
        "weight_new": "30",
        "height_new": "1.08",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey20",
        "species": "Pidgey",
        "cp": "176",
        "hp": "35",
        "weight": "1.81",
        "height": "0.29",
        "power_up_stardust": "1000",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "327",
        "hp_new": "54",
        "weight_new": "3.46",
        "height_new": "1.07",
        "power_up_stardust_new": "1000",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey21",
        "species": "Pidgey",
        "cp": "97",
        "hp": "30",
        "weight": "1.95",
        "height": "0.31",
        "power_up_stardust": "600",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "181",
        "hp_new": "44",
        "weight_new": "1.79",
        "height_new": "1.15",
        "power_up_stardust_new": "600",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey22",
        "species": "Pidgey",
        "cp": "74",
        "hp": "24",
        "weight": "0.78",
        "height": "0.26",
        "power_up_stardust": "600",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "141",
        "hp_new": "38",
        "weight_new": "30",
        "height_new": "0.95",
        "power_up_stardust_new": "600",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey23",
        "species": "Pidgey",
        "cp": "127",
        "hp": "32",
        "weight": "2.33",
        "height": "0.34",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "241",
        "hp_new": "49",
        "weight_new": "3.4",
        "height_new": "1.23",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey24",
        "species": "Pidgey",
        "cp": "78",
        "hp": "26",
        "weight": "2.11",
        "height": "0.32",
        "power_up_stardust": "600",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "146",
        "hp_new": "39",
        "weight_new": "3.16",
        "height_new": "1.17",
        "power_up_stardust_new": "600",
        "power_up_candy_new": "1",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey25",
        "species": "Pidgey",
        "cp": "240",
        "hp": "41",
        "weight": "2.53",
        "height": "0.33",
        "power_up_stardust": "1600",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "448",
        "hp_new": "64",
        "weight_new": "8.21",
        "height_new": "1.21",
        "power_up_stardust_new": "1600",
        "power_up_candy_new": "2",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey26",
        "species": "Pidgey",
        "cp": "276",
        "hp": "48",
        "weight": "0.87",
        "height": "0.24",
        "power_up_stardust": "2200",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "530",
        "hp_new": "74",
        "weight_new": "30",
        "height_new": "0.86",
        "power_up_stardust_new": "2200",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey27",
        "species": "Pidgey",
        "cp": "207",
        "hp": "41",
        "weight": "1.19",
        "height": "0.26",
        "power_up_stardust": "1600",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "393",
        "hp_new": "64",
        "weight_new": "30",
        "height_new": "0.96",
        "power_up_stardust_new": "1600",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey28",
        "species": "Pidgey",
        "cp": "176",
        "hp": "35",
        "weight": "1.68",
        "height": "0.31",
        "power_up_stardust": "1300",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "335",
        "hp_new": "55",
        "weight_new": "30",
        "height_new": "1.13",
        "power_up_stardust_new": "1300",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey29",
        "species": "Pidgey",
        "cp": "316",
        "hp": "47",
        "weight": "1.71",
        "height": "0.27",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "594",
        "hp_new": "74",
        "weight_new": "5.71",
        "height_new": "0.99",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey30",
        "species": "Pidgey",
        "cp": "305",
        "hp": "53",
        "weight": "2.04",
        "height": "0.32",
        "power_up_stardust": "2200",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "567",
        "hp_new": "79",
        "weight_new": "1.95",
        "height_new": "1.17",
        "power_up_stardust_new": "2200",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey31",
        "species": "Pidgey",
        "cp": "304",
        "hp": "46",
        "weight": "1.99",
        "height": "0.31",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "579",
        "hp_new": "73",
        "weight_new": "3.88",
        "height_new": "1.12",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey32",
        "species": "Pidgey",
        "cp": "242",
        "hp": "43",
        "weight": "2.09",
        "height": "0.34",
        "power_up_stardust": "1900",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "459",
        "hp_new": "67",
        "weight_new": "30",
        "height_new": "1.26",
        "power_up_stardust_new": "1900",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey33",
        "species": "Pidgey",
        "cp": "250",
        "hp": "42",
        "weight": "0.95",
        "height": "0.26",
        "power_up_stardust": "1900",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "471",
        "hp_new": "66",
        "weight_new": "30",
        "height_new": "0.95",
        "power_up_stardust_new": "1900",
        "power_up_candy_new": "2",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey34",
        "species": "Pidgey",
        "cp": "226",
        "hp": "40",
        "weight": "2.04",
        "height": "0.31",
        "power_up_stardust": "1600",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "428",
        "hp_new": "63",
        "weight_new": "4.76",
        "height_new": "1.12",
        "power_up_stardust_new": "1600",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey35",
        "species": "Pidgey",
        "cp": "220",
        "hp": "43",
        "weight": "2.13",
        "height": "0.3",
        "power_up_stardust": "1600",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "418",
        "hp_new": "66",
        "weight_new": "7.41",
        "height_new": "1.1",
        "power_up_stardust_new": "1600",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey36",
        "species": "Pidgey",
        "cp": "185",
        "hp": "40",
        "weight": "1.63",
        "height": "0.29",
        "power_up_stardust": "1300",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Twister",
        "attack_strong_type": "Dragon",
        "attack_strong_value": "25",
        "cp_new": "354",
        "hp_new": "62",
        "weight_new": "0.53",
        "height_new": "1.07",
        "power_up_stardust_new": "1300",
        "power_up_candy_new": "2",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey37",
        "species": "Pidgey",
        "cp": "42",
        "hp": "20",
        "weight": "2.11",
        "height": "0.33",
        "power_up_stardust": "400",
        "power_up_candy": "1",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "80",
        "hp_new": "30",
        "weight_new": "1.02",
        "height_new": "1.21",
        "power_up_stardust_new": "400",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Aerial Ace",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Pidgey38",
        "species": "Pidgey",
        "cp": "344",
        "hp": "56",
        "weight": "2.57",
        "height": "0.35",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Aerial Ace",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "647",
        "hp_new": "84",
        "weight_new": "4.16",
        "height_new": "1.29",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Steel Wing",
        "attack_weak_type_new": "Steel",
        "attack_weak_value_new": "15",
        "attack_strong_new": "Twister",
        "attack_strong_type_new": "Dragon",
        "attack_strong_value_new": "25",
        "notes": ""
    },
    {
        "name": "Pidgey39",
        "species": "Pidgey",
        "cp": "108",
        "hp": "31",
        "weight": "1.19",
        "height": "0.25",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Air Cutter",
        "attack_strong_type": "Flying",
        "attack_strong_value": "30",
        "cp_new": "205",
        "hp_new": "47",
        "weight_new": "0.54",
        "height_new": "0.91",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Wing Attack",
        "attack_weak_type_new": "Flying",
        "attack_weak_value_new": "9",
        "attack_strong_new": "Air Cutter",
        "attack_strong_type_new": "Flying",
        "attack_strong_value_new": "30",
        "notes": ""
    },
    {
        "name": "Weedle1",
        "species": "Weedle",
        "cp": "169",
        "hp": "45",
        "weight": "3.38",
        "height": "0.29",
        "power_up_stardust": "2200",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "185",
        "hp_new": "51",
        "weight_new": "4.18",
        "height_new": "0.58",
        "power_up_stardust_new": "2200",
        "power_up_candy_new": "2",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle2",
        "species": "Weedle",
        "cp": "15",
        "hp": "15",
        "weight": "3.27",
        "height": "0.28",
        "power_up_stardust": "200",
        "power_up_candy": "1",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "16",
        "hp_new": "17",
        "weight_new": "4.48",
        "height_new": "0.55",
        "power_up_stardust_new": "200",
        "power_up_candy_new": "1",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle3",
        "species": "Weedle",
        "cp": "25",
        "hp": "17",
        "weight": "3.11",
        "height": "0.29",
        "power_up_stardust": "400",
        "power_up_candy": "1",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "27",
        "hp_new": "19",
        "weight_new": "3.45",
        "height_new": "0.58",
        "power_up_stardust_new": "400",
        "power_up_candy_new": "1",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle4",
        "species": "Weedle",
        "cp": "222",
        "hp": "48",
        "weight": "2.93",
        "height": "0.29",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "245",
        "hp_new": "54",
        "weight_new": "2.64",
        "height_new": "0.59",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle5",
        "species": "Weedle",
        "cp": "251",
        "hp": "56",
        "weight": "4.51",
        "height": "0.34",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "272",
        "hp_new": "62",
        "weight_new": "5.52",
        "height_new": "0.67",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle6",
        "species": "Weedle",
        "cp": "139",
        "hp": "46",
        "weight": "4.5",
        "height": "0.32",
        "power_up_stardust": "1900",
        "power_up_candy": "2",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "151",
        "hp_new": "51",
        "weight_new": "6.29",
        "height_new": "0.64",
        "power_up_stardust_new": "1900",
        "power_up_candy_new": "2",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle7",
        "species": "Weedle",
        "cp": "45",
        "hp": "27",
        "weight": "2.55",
        "height": "0.29",
        "power_up_stardust": "600",
        "power_up_candy": "1",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "49",
        "hp_new": "30",
        "weight_new": "1.65",
        "height_new": "0.58",
        "power_up_stardust_new": "600",
        "power_up_candy_new": "1",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle8",
        "species": "Weedle",
        "cp": "129",
        "hp": "45",
        "weight": "4.01",
        "height": "0.34",
        "power_up_stardust": "1600",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "140",
        "hp_new": "50",
        "weight_new": "3.53",
        "height_new": "0.69",
        "power_up_stardust_new": "1600",
        "power_up_candy_new": "2",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle9",
        "species": "Weedle",
        "cp": "200",
        "hp": "49",
        "weight": "2.62",
        "height": "0.27",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "217",
        "hp_new": "55",
        "weight_new": "2.52",
        "height_new": "0.55",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle10",
        "species": "Weedle",
        "cp": "179",
        "hp": "47",
        "weight": "3.95",
        "height": "0.35",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "193",
        "hp_new": "53",
        "weight_new": "3.21",
        "height_new": "0.7",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle11",
        "species": "Weedle",
        "cp": "104",
        "hp": "36",
        "weight": "3.48",
        "height": "0.31",
        "power_up_stardust": "1300",
        "power_up_candy": "2",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "113",
        "hp_new": "41",
        "weight_new": "3.82",
        "height_new": "0.61",
        "power_up_stardust_new": "1300",
        "power_up_candy_new": "2",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle12",
        "species": "Weedle",
        "cp": "144",
        "hp": "48",
        "weight": "2.6",
        "height": "0.29",
        "power_up_stardust": "1900",
        "power_up_candy": "2",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "157",
        "hp_new": "53",
        "weight_new": "1.87",
        "height_new": "0.57",
        "power_up_stardust_new": "1900",
        "power_up_candy_new": "2",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle13",
        "species": "Weedle",
        "cp": "157",
        "hp": "49",
        "weight": "2.05",
        "height": "0.28",
        "power_up_stardust": "2200",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "172",
        "hp_new": "54",
        "weight_new": "0.42",
        "height_new": "0.56",
        "power_up_stardust_new": "2200",
        "power_up_candy_new": "2",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle14",
        "species": "Weedle",
        "cp": "106",
        "hp": "39",
        "weight": "5.31",
        "height": "0.39",
        "power_up_stardust": "1300",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "115",
        "hp_new": "43",
        "weight_new": "5.39",
        "height_new": "0.77",
        "power_up_stardust_new": "1300",
        "power_up_candy_new": "2",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle15",
        "species": "Weedle",
        "cp": "203",
        "hp": "52",
        "weight": "3.54",
        "height": "0.3",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "219",
        "hp_new": "58",
        "weight_new": "4.38",
        "height_new": "0.59",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle16",
        "species": "Weedle",
        "cp": "16",
        "hp": "13",
        "weight": "2.68",
        "height": "0.26",
        "power_up_stardust": "200",
        "power_up_candy": "1",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "18",
        "hp_new": "15",
        "weight_new": "3.27",
        "height_new": "0.52",
        "power_up_stardust_new": "200",
        "power_up_candy_new": "1",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle17",
        "species": "Weedle",
        "cp": "240",
        "hp": "54",
        "weight": "4.33",
        "height": "0.35",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "260",
        "hp_new": "60",
        "weight_new": "4.05",
        "height_new": "0.71",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle18",
        "species": "Weedle",
        "cp": "60",
        "hp": "27",
        "weight": "3.46",
        "height": "0.32",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "66",
        "hp_new": "31",
        "weight_new": "3.26",
        "height_new": "0.63",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle19",
        "species": "Weedle",
        "cp": "80",
        "hp": "35",
        "weight": "1.69",
        "height": "0.22",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Poison Sting",
        "attack_weak_type": "Poison",
        "attack_weak_value": "6",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "86",
        "hp_new": "39",
        "weight_new": "1.62",
        "height_new": "0.44",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Poison Sting",
        "attack_weak_type_new": "Poison",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Weedle20",
        "species": "Weedle",
        "cp": "75",
        "hp": "30",
        "weight": "3.52",
        "height": "0.35",
        "power_up_stardust": "800",
        "power_up_candy": "1",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "81",
        "hp_new": "34",
        "weight_new": "1.87",
        "height_new": "0.7",
        "power_up_stardust_new": "800",
        "power_up_candy_new": "1",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie1",
        "species": "Caterpie",
        "cp": "136",
        "hp": "44",
        "weight": "4.68",
        "height": "0.35",
        "power_up_stardust": "1600",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "150",
        "hp_new": "49",
        "weight_new": "6.33",
        "height_new": "0.82",
        "power_up_stardust_new": "1600",
        "power_up_candy_new": "2",
        "attack_weak_new": "Tackle",
        "attack_weak_type_new": "Normal",
        "attack_weak_value_new": "12",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie2",
        "species": "Caterpie",
        "cp": "231",
        "hp": "62",
        "weight": "3.8",
        "height": "0.32",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "248",
        "hp_new": "68",
        "weight_new": "4.98",
        "height_new": "0.75",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Tackle",
        "attack_weak_type_new": "Normal",
        "attack_weak_value_new": "12",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie3",
        "species": "Caterpie",
        "cp": "43",
        "hp": "26",
        "weight": "2.68",
        "height": "0.28",
        "power_up_stardust": "600",
        "power_up_candy": "1",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "46",
        "hp_new": "29",
        "weight_new": "3.12",
        "height_new": "0.65",
        "power_up_stardust_new": "600",
        "power_up_candy_new": "1",
        "attack_weak_new": "Tackle",
        "attack_weak_type_new": "Normal",
        "attack_weak_value_new": "12",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie4",
        "species": "Caterpie",
        "cp": "140",
        "hp": "49",
        "weight": "2.7",
        "height": "0.3",
        "power_up_stardust": "1900",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "151",
        "hp_new": "54",
        "weight_new": "2.1",
        "height_new": "0.71",
        "power_up_stardust_new": "1900",
        "power_up_candy_new": "2",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie5",
        "species": "Caterpie",
        "cp": "208",
        "hp": "53",
        "weight": "2.24",
        "height": "0.29",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "226",
        "hp_new": "59",
        "weight_new": "1.29",
        "height_new": "0.67",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Tackle",
        "attack_weak_type_new": "Normal",
        "attack_weak_value_new": "12",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie6",
        "species": "Caterpie",
        "cp": "128",
        "hp": "46",
        "weight": "1.69",
        "height": "0.24",
        "power_up_stardust": "1600",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "137",
        "hp_new": "51",
        "weight_new": "1.17",
        "height_new": "0.57",
        "power_up_stardust_new": "1600",
        "power_up_candy_new": "2",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie7",
        "species": "Caterpie",
        "cp": "186",
        "hp": "56",
        "weight": "3.14",
        "height": "0.27",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "200",
        "hp_new": "63",
        "weight_new": "4.92",
        "height_new": "0.64",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Tackle",
        "attack_weak_type_new": "Normal",
        "attack_weak_value_new": "12",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie8",
        "species": "Caterpie",
        "cp": "149",
        "hp": "46",
        "weight": "2.69",
        "height": "0.31",
        "power_up_stardust": "1900",
        "power_up_candy": "2",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "161",
        "hp_new": "51",
        "weight_new": "1.78",
        "height_new": "0.72",
        "power_up_stardust_new": "1900",
        "power_up_candy_new": "2",
        "attack_weak_new": "Tackle",
        "attack_weak_type_new": "Normal",
        "attack_weak_value_new": "12",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie9",
        "species": "Caterpie",
        "cp": "10",
        "hp": "10",
        "weight": "1.87",
        "height": "0.29",
        "power_up_stardust": "200",
        "power_up_candy": "1",
        "attack_weak": "Bug Bite",
        "attack_weak_type": "Bug",
        "attack_weak_value": "5",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "10",
        "hp_new": "10",
        "weight_new": "9.9",
        "height_new": "0.69",
        "power_up_stardust_new": "200",
        "power_up_candy_new": "1",
        "attack_weak_new": "Tackle",
        "attack_weak_type_new": "Normal",
        "attack_weak_value_new": "12",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Caterpie10",
        "species": "Caterpie",
        "cp": "86",
        "hp": "10",
        "weight": "3.5",
        "height": "0.3",
        "power_up_stardust": "1000",
        "power_up_candy": "1",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Struggle",
        "attack_strong_type": "Normal",
        "attack_strong_value": "15",
        "cp_new": "92",
        "hp_new": "45",
        "weight_new": "4.85",
        "height_new": "0.7",
        "power_up_stardust_new": "1000",
        "power_up_candy_new": "1",
        "attack_weak_new": "Bug Bite",
        "attack_weak_type_new": "Bug",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Struggle",
        "attack_strong_type_new": "Normal",
        "attack_strong_value_new": "15",
        "notes": ""
    },
    {
        "name": "Eevee1",
        "species": "Eevee",
        "cp": "619",
        "hp": "74",
        "weight": "2.87",
        "height": "0.2",
        "power_up_stardust": "3000",
        "power_up_candy": "3",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Body Slam",
        "attack_strong_type": "Normal",
        "attack_strong_value": "40",
        "cp_new": "1646",
        "hp_new": "165",
        "weight_new": "2.49",
        "height_new": "0.68",
        "power_up_stardust_new": "3000",
        "power_up_candy_new": "3",
        "attack_weak_new": "Water Gun",
        "attack_weak_type_new": "Water",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Aqua Tail",
        "attack_strong_type_new": "Water",
        "attack_strong_value_new": "45",
        "notes": "Vaporean, attack details added on date later than evolution"
    },
    {
        "name": "Eevee3",
        "species": "Eevee",
        "cp": "500",
        "hp": "64",
        "weight": "5.11",
        "height": "0.26",
        "power_up_stardust": "2200",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Dig",
        "attack_strong_type": "Ground",
        "attack_strong_value": "70",
        "cp_new": "1253",
        "hp_new": "75",
        "weight_new": "6.06",
        "height_new": "0.77",
        "power_up_stardust_new": "2200",
        "power_up_candy_new": "2",
        "attack_weak_new": "Ember",
        "attack_weak_type_new": "Fire",
        "attack_weak_value_new": "10",
        "attack_strong_new": "Fire Blast",
        "attack_strong_type_new": "Fire",
        "attack_strong_value_new": "100",
        "notes": "Jolteon, attack details added on date later than evolution"
    },
    {
        "name": "Eevee7",
        "species": "Eevee",
        "cp": "606",
        "hp": "74",
        "weight": "10.42",
        "height": "0.38",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Swift",
        "attack_strong_type": "Normal",
        "attack_strong_value": "30",
        "cp_new": "1591",
        "hp_new": "164",
        "weight_new": "10.55",
        "height_new": "1.26",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Water Gun",
        "attack_weak_type_new": "Water",
        "attack_weak_value_new": "6",
        "attack_strong_new": "Aqua Tail",
        "attack_strong_type_new": "Water",
        "attack_strong_value_new": "45",
        "notes": "Vaporeon, attack details added on date later than evolution"
    },
    {
        "name": "Eevee8",
        "species": "Eevee",
        "cp": "548",
        "hp": "66",
        "weight": "6.87",
        "height": "0.32",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Body Slam",
        "attack_strong_type": "Normal",
        "attack_strong_value": "40",
        "cp_new": "1362",
        "hp_new": "78",
        "weight_new": "5.63",
        "height_new": "0.95",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Ember",
        "attack_weak_type_new": "Fire",
        "attack_weak_value_new": "10",
        "attack_strong_new": "Heat Wave",
        "attack_strong_type_new": "Fire",
        "attack_strong_value_new": "80",
        "notes": "Flareon, attack details added on date later than evolution"
    },
    {
        "name": "Eevee9",
        "species": "Eevee",
        "cp": "528",
        "hp": "66",
        "weight": "7.43",
        "height": "0.31",
        "power_up_stardust": "2200",
        "power_up_candy": "2",
        "attack_weak": "Quick Attack",
        "attack_weak_type": "Normal",
        "attack_weak_value": "10",
        "attack_strong": "Dig",
        "attack_strong_type": "Ground",
        "attack_strong_value": "70",
        "cp_new": "1059",
        "hp_new": "78",
        "weight_new": "8.93",
        "height_new": "0.82",
        "power_up_stardust_new": "2200",
        "power_up_candy_new": "2",
        "attack_weak_new": "Thunder Shock",
        "attack_weak_type_new": "Electric",
        "attack_weak_value_new": "5",
        "attack_strong_new": "Thunderbolt",
        "attack_strong_type_new": "Electric",
        "attack_strong_value_new": "55",
        "notes": "Jolteon, attack details added on date later than evolution"
    },
    {
        "name": "Eevee10",
        "species": "Eevee",
        "cp": "517",
        "hp": "72",
        "weight": "6.63",
        "height": "0.29",
        "power_up_stardust": "2500",
        "power_up_candy": "2",
        "attack_weak": "Tackle",
        "attack_weak_type": "Normal",
        "attack_weak_value": "12",
        "attack_strong": "Body Slam",
        "attack_strong_type": "Normal",
        "attack_strong_value": "40",
        "cp_new": "1340",
        "hp_new": "84",
        "weight_new": "7.75",
        "height_new": "0.88",
        "power_up_stardust_new": "2500",
        "power_up_candy_new": "2",
        "attack_weak_new": "Ember",
        "attack_weak_type_new": "Fire",
        "attack_weak_value_new": "10",
        "attack_strong_new": "Heat Wave",
        "attack_strong_type_new": "Fire",
        "attack_strong_value_new": "80",
        "notes": "Flareon, attack details added on date later than evolution"
    }
]
